services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app           # code backend
      - db-data:/app/database    # volume pour SQLite
    environment:
      NODE_ENV: development
    restart: unless-stopped


  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    restart: unless-stopped

volumes:
  db-data: