services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app           # code backend
      - db-data:/app/database    # volume pour SQLite
      - /app/node_modules
    environment:
      NODE_ENV: development
    restart: unless-stopped


  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0 --port 5173 --strictPort
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  db-data: