services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app           # code backend
      - db-data:/app/database    # volume pour SQLite
      - /app/node_modules        # Protège node_modules
    environment:
      NODE_ENV: development
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app_network
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - app_network
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    restart: unless-stopped

volumes:
  db-data:

networks:
  app_network:   # ou app-network, mais assurer le même nom partout
    driver: bridge
