# Étape 1 : choisir une image Node officielle
FROM node:22-alpine

# Étape 2 : définir le dossier de travail dans le conteneur
WORKDIR /app

COPY . .

RUN mkdir -p database && chown -R node:node database


# Deps pour node-gyp + SQLite (musl)
RUN apk add --no-cache python3 make g++ pkgconfig sqlite sqlite-dev

# Étape 4 : installer les dépendances
RUN npm ci
RUN apk add curl

# Étape 5 : 
RUN npx prisma generate

# Étape 6 : exposer le port du serveur (3000)
EXPOSE 3000

# Étape 7 : commande par défaut pour lancer ton serveur
# CMD ["npm", "run", "dev"]
CMD ["sh", "-c", "npx prisma db push && npm run dev"]
