{
 "title": "API Performance Dashboard",
 "description": "Get information for api performance",
 "tags": [
  "api",
  "performance",
  "monitoring"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "API ROUTES",
   "type": "table",
   "description": "Show active API",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (route) (http_requests_total)\n"
    }
   ]
  },
  {
   "title": "Top 10 Slowest APIs (Avg Latency)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  histogram_quantile(\n    0.95,\n    sum by (le, route, method) (\n      rate(http_request_duration_seconds_bucket{status_code=~\"2..\"}[$__range])\n    )\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Top 5 Busiest APIs (RPS)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(\n  5,\n  sum by (route, method) (\n    rate(http_requests_total[$__range])\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Longest Requests (Max Latency)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  histogram_quantile(\n    0.95,\n    sum by (le, route, method) (\n      rate(http_request_duration_seconds_bucket{status_code=~\"2..\"}[$__range])\n    )\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (route, method) (\n  rate(http_requests_total[5m])\n)\n",
     "legendFormat": "Total RPS"
    }
   ]
  }
 ]
}