{
 "title": "Backend_Monitoring",
 "description": "Get information for api performance",
 "tags": [
  "api",
  "performance",
  "monitoring"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Backend Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"backend\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP ERRORS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_requests_total{status_code=~\"5..\"}[$__rate_interval])) or vector(0)\n)\n/\nclamp_min(sum(rate(http_requests_total[$__rate_interval])), 1)\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API ROUTES",
   "type": "table",
   "description": "Show active API",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (route) (http_requests_total)\n"
    }
   ]
  },
  {
   "title": "Top 10 Slowest APIs (Avg Latency)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  histogram_quantile(\n    0.95,\n    sum by (le, route, method) (\n      rate(http_request_duration_seconds_bucket{status_code=~\"2..\"}[$__range])\n    )\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Top 5 Busiest APIs (RPS)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(\n  5,\n  sum by (route, method) (\n    rate(http_requests_total[$__range])\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Longest Requests (Max Latency)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  histogram_quantile(\n    0.95,\n    sum by (le, route, method) (\n      rate(http_request_duration_seconds_bucket{status_code=~\"2..\"}[$__range])\n    )\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (route, method) (\n  rate(http_requests_total[5m])\n)\n",
     "legendFormat": "Total RPS"
    }
   ]
  },
  {
   "title": "Prisma Queries per Second (QPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(prisma_queries_total[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prisma Queries by Modell",
   "type": "barchart",
   "description": "“Which models are being hit?”",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum by (model) (\n  rate(prisma_queries_total[5m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Prisma Query Duration",
   "type": "timeseries",
   "description": "“How slow is my DB on average?”",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(prisma_query_duration_seconds_sum[1m]))\n/\nsum(rate(prisma_query_duration_seconds_count[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prisma Errors Rate (Per second)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(prisma_errors_total[5m])", "legendFormat": "__auto" }
   ]
  }
 ]
}